### ISSUE TITLE
Casual code review

### ISSUE THREAD

**Issue by 0xabad1dea** [jan-matejka/cbugzilla#2]
https://github.com/yaccz/cbugzilla/blob/master/src/main.c#L45
buf is not necessarily null-terminated, out of bounds may ensue

https://github.com/yaccz/cbugzilla/blob/master/src/bugzilla.c#L80
headline is alloced 100 and the sprintf of namedcmd not length-checked

https://github.com/yaccz/cbugzilla/blob/master/src/string.c#L13
why only the first time? I may have missed something... 

https://github.com/yaccz/cbugzilla/blob/master/src/bugzilla_parser.c#L54
While currently harmless, I'd recommend putting in a sanity check around the returned count

https://github.com/yaccz/cbugzilla/blob/master/src/cb.c#L29
Is response.len guaranteed to > 0? If not you'll get a 2GB log file :D 

:sparkling_heart:

**Comment by jan-matejka** [comment]
> https://github.com/yaccz/cbugzilla/blob/master/src/string.c#L13
> why only the first time? I may have missed something...

This function evolved kinda messily, I suppose the original intent was to have `len_delta` instead of  `len`

> https://github.com/yaccz/cbugzilla/blob/master/src/cb.c#L29
> Is response.len guaranteed to > 0? If not you'll get a 2GB log file :D

I don't see how fwrite would write lot of stuff when given negative nmbemb.
https://github.com/yaccz/code-snippets/blob/master/c/fwrite_negative_nmemb/main.c
This gives me empty file with written = 0

Thanks for the review.
